{
 "title": "Kafka/Network",
 "tags": [ "kafka" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "kafka_network_request_duration_milliseconds"
   },
   {
    "name": "queue",
    "label": "Queue",
    "query": "kafka_network_request_channel_queue_size"
   },
   { "name": "request", "label": "Request", "query": "kafka_network_request_count" },
   {
    "name": "scope",
    "label": "Scope",
    "query": "kafka_network_request_duration_milliseconds"
   },
   {
    "name": "percentile",
    "label": "Percentile",
    "query": "kafka_network_request_duration_milliseconds"
   }
  ]
 },
 "panels": [
  {
   "title": "Request count",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_network_request_count{instance=\"$instance\",job=\"kafka-jmx\",request=\"$request\"}[7m])"
    }
   ]
  },
  {
   "title": "Queue size",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_network_request_channel_queue_size{instance=\"$instance\",job=\"kafka-jmx\",queue=\"$queue\"}"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_request_duration_milliseconds{instance=\"$instance\",job=\"kafka-jmx\",percentile=\"$percentile\",request=\"$request\",scope=\"$scope\"}"
    }
   ]
  }
 ]
}