{
 "title": "Kafka/Server",
 "tags": [ "kafka" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "kafka_server_broker_topic_bytesin_count_total"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "kafka_server_broker_topic_bytesin_count"
   },
   {
    "name": "operation",
    "label": "Operation",
    "query": "kafka_server_delayed_operation_purgatory_numdelayedoperations"
   },
   {
    "name": "client_id",
    "label": "Client id",
    "query": "kafka_server_fetcher_lag_consumerlag"
   },
   {
    "name": "partition",
    "label": "Partition",
    "query": "kafka_server_fetcher_lag_consumerlag"
   },
   {
    "name": "consumer_lag_topic",
    "label": "Consumer lag topic",
    "query": "kafka_server_fetcher_lag_consumerlag"
   },
   {
    "name": "client_state",
    "label": "Zookeeper client state",
    "query": "kafka_server_zookeeper_clientstate_count"
   }
  ]
 },
 "panels": [
  {
   "title": "Broker stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Under-replicated partitions",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
     "format": "short",
     "valueName": "avg",
     "targets": [
      {
       "expr": "kafka_server_replication_underreplicatedpartitions{instance=\"$instance\",job=\"kafka-jmx\"}"
      }
     ]
    },
    {
     "title": "Replication ISR expands",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
     "format": "short",
     "valueName": "avg",
     "targets": [
      {
       "expr": "kafka_server_replication_isrexpands_count{instance=\"$instance\",job=\"kafka-jmx\"}"
      }
     ]
    },
    {
     "title": "Replication ISR shrinks",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
     "format": "short",
     "valueName": "avg",
     "targets": [
      {
       "expr": "kafka_server_replication_isrshrinks_count{instance=\"$instance\",job=\"kafka-jmx\"}"
      }
     ]
    },
    {
     "title": "Replication leader count",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
     "format": "short",
     "valueName": "avg",
     "targets": [
      {
       "expr": "kafka_server_replication_leadercount{instance=\"$instance\",job=\"kafka-jmx\"}"
      }
     ]
    },
    {
     "title": "Replication partition count",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
     "format": "short",
     "valueName": "avg",
     "targets": [
      {
       "expr": "kafka_server_replication_partitioncount{instance=\"$instance\",job=\"kafka-jmx\"}"
      }
     ]
    },
    {
     "title": "Broker state",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
     "format": "short",
     "valueName": "avg",
     "targets": [
      {
       "expr": "kafka_server_brokerstate{instance=\"$instance\",job=\"kafka-jmx\"}"
      }
     ]
    },
    {
     "title": "Zookeeper client state count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_server_zookeeper_clientstate_count{client_state=\"$client_state\",instance=\"$instance\",job=\"kafka-jmx\"}"
      }
     ]
    },
    {
     "title": "Fetcher consumer lag",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_server_fetcher_lag_consumerlag{client_id=\"$client_id\",instance=\"$instance\",job=\"kafka-jmx\",partition=\"$partition\",topic=\"$consumer_lag_topic\"}"
      }
     ]
    },
    {
     "title": "Delayed purgatory operation size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kafka_server_delayed_operation_purgatory_purgatorysize{instance=\"$instance\",job=\"kafka-jmx\",operation=\"$operation\"}"
      }
     ]
    },
    {
     "title": "Delayed fetch expires count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_server_delayed_fetch_expires_count{instance=\"$instance\",job=\"kafka-jmx\"}"
      }
     ]
    },
    {
     "title": "Number of delayed purgatory operations",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_server_delayed_operation_purgatory_numdelayedoperations{instance=\"$instance\",job=\"kafka-jmx\",operation=\"$operation\"}"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 25 }, "content": "# Broker Topic Metrics" }
   ]
  },
  { "title": "Topic total counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Total bytes in",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 2 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_server_broker_topic_bytesin_count_total{instance=\"$instance\",job=\"kafka-jmx\"}"
    }
   ]
  },
  {
   "title": "Total bytes out",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 2 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_server_broker_topic_bytesout_count_total{instance=\"$instance\",job=\"kafka-jmx\"}"
    }
   ]
  },
  {
   "title": "Total bytes rejected",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 2 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_server_broker_topic_bytesrejected_count_total{instance=\"$instance\",job=\"kafka-jmx\"}"
    }
   ]
  },
  {
   "title": "Total failed fetch requests",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 2 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_server_broker_topic_failedfetchrequests_count_total{instance=\"$instance\",job=\"kafka-jmx\"}"
    }
   ]
  },
  {
   "title": "Total failed producer requests",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_server_broker_topic_failedproducerequests_count_total{instance=\"$instance\",job=\"kafka-jmx\"}"
    }
   ]
  },
  {
   "title": "Total messages in",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 11 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_server_broker_topic_messagesin_count_total{instance=\"$instance\",job=\"kafka-jmx\"}"
    }
   ]
  },
  {
   "title": "Total fetch requests",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 11 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_server_broker_topic_totalfetchrequests_count_total{instance=\"$instance\",job=\"kafka-jmx\"}"
    }
   ]
  },
  {
   "title": "Total producer requests",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_server_broker_topic_totalproducerequests_count_total{instance=\"$instance\",job=\"kafka-jmx\"}"
    }
   ]
  },
  {
   "title": "Topic metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes in",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kafka_server_broker_topic_bytesin_count{instance=\"$instance\",job=\"kafka-jmx\",topic=\"$topic\"}"
      }
     ]
    },
    {
     "title": "Bytes out",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kafka_server_broker_topic_bytesout_count{instance=\"$instance\",job=\"kafka-jmx\",topic=\"$topic\"}"
      }
     ]
    },
    {
     "title": "Bytes rejected",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kafka_server_broker_topic_bytesrejected_count{instance=\"$instance\",job=\"kafka-jmx\",topic=\"$topic\"}"
      }
     ]
    },
    {
     "title": "Failed fetch requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_server_broker_topic_failedfetchrequests_count{instance=\"$instance\",job=\"kafka-jmx\",topic=\"$topic\"}"
      }
     ]
    },
    {
     "title": "Failed producer requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_server_broker_topic_failedproducerequests_count{instance=\"$instance\",job=\"kafka-jmx\",topic=\"$topic\"}"
      }
     ]
    },
    {
     "title": "Messages in",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_server_broker_topic_messagesin_count{instance=\"$instance\",job=\"kafka-jmx\",topic=\"$topic\"}"
      }
     ]
    },
    {
     "title": "Fetch requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_server_broker_topic_totalfetchrequests_count{instance=\"$instance\",job=\"kafka-jmx\",topic=\"$topic\"}[5m])"
      }
     ]
    },
    {
     "title": "Producer requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_server_broker_topic_totalproducerequests_count{instance=\"$instance\",job=\"kafka-jmx\",topic=\"$topic\"}"
      }
     ]
    }
   ]
  }
 ]
}