{
 "title": "Kafka/Log",
 "tags": [ "kafka" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": "kafka_log_size" },
   { "name": "topic", "label": "Topic", "query": "kafka_log_size" },
   { "name": "partition", "label": "Partition", "query": "kafka_log_size" },
   {
    "name": "percentile",
    "label": "Percentile",
    "query": "kafka_log_flush_time_milliseconds"
   },
   { "name": "offsets_topic", "label": "Offsets topic", "query": "kafka_log_logendoffset" }
  ]
 },
 "panels": [
  {
   "title": "Log size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log size",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kafka_log_size{job=\"kafka-jmx\",partition=\"0\",topic=\"$topic\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Flush",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flush count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_log_flush_count{job=\"kafka-jmx\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Flush time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_log_flush_time_milliseconds{job=\"kafka-jmx\",percentile=\"$percentile\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Offset",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Log start offset",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_log_logstartoffset{job=\"kafka-jmx\",partition=\"$partition\",topic=\"$offsets_topic\"}"
      }
     ]
    },
    {
     "title": "Log end offset",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_log_logendoffset{job=\"kafka-jmx\",partition=\"$partition\",topic=\"$offsets_topic\"}"
      }
     ]
    }
   ]
  }
 ]
}