{
 "title": "Kafka/Controller",
 "tags": [ "kafka" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "kafka_controller_activecontrollercount"
   }
  ]
 },
 "panels": [
  {
   "title": "Active controller count",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_controller_activecontrollercount{instance=\"$instance\",job=\"kafka-jmx\"}"
    }
   ]
  },
  {
   "title": "Leader election count",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_controller_leaderelection_count{instance=\"$instance\",job=\"kafka-jmx\"}"
    }
   ]
  },
  {
   "title": "Preferred replication balance count",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_controller_preferredreplicaimbalancecount{instance=\"$instance\",job=\"kafka-jmx\"}"
    }
   ]
  },
  {
   "title": "Offline partition count",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_controller_offlinepartitionscount{instance=\"$instance\",job=\"kafka-jmx\"}"
    }
   ]
  },
  {
   "title": "Unclean leader election count",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_controller_uncleanleaderelection_count{instance=\"$instance\",job=\"kafka-jmx\"}"
    }
   ]
  }
 ]
}