{
 "title": "Logs - Fluentd Statistics",
 "tags": [ "fluentd" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Logs per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_output_status_emit_records[5m])) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }} "
    },
    {
     "expr": "sum(rate(fluentd_records_total[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Average queue length over 5m",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(fluentd_status_buffer_queue_length[5m])) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Average queue size over 5m",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(fluentd_status_buffer_total_bytes[5m])) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Retries",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fluentd_status_retry_count[5m]))",
     "legendFormat": "Retries"
    }
   ]
  }
 ]
}